-- ANALYZE
WITH DEPT_ANALYSIS AS (
    SELECT DEPARTMENT_ID, COUNT(*) AS NUM_EMPLOYEES, AVG(SALARY) AS AVG_SALARY
    FROM HR.EMPLOYEES
    GROUP BY DEPARTMENT_ID
)
SELECT DEPARTMENT_ID,
       CASE
           WHEN NUM_EMPLOYEES > 30 THEN 'Splitting the Department'
           WHEN AVG_SALARY > 10000 THEN 'Review Salary Structure'
           ELSE 'All Good'
       END AS SUGGESTION
FROM DEPT_ANALYSIS;
