-- CREATE A HIERARCHICAL VIEW OF THE ORGANIZATION
SELECT LEVEL AS HIERARCHY_LEVEL,
       E.EMPLOYEE_ID,
       E.FIRST_NAME || ' ' || E.LAST_NAME AS EMPLOYEE_NAME,
       M.FIRST_NAME || ' ' || M.LAST_NAME AS MANAGER_NAME,
       D.DEPARTMENT_NAME
FROM HR.EMPLOYEES E
INNER JOIN HR.DEPARTMENTS D ON E.DEPARTMENT_ID = D.DEPARTMENT_ID
LEFT JOIN HR.EMPLOYEES M ON E.MANAGER_ID = M.EMPLOYEE_ID
CONNECT BY PRIOR E.EMPLOYEE_ID = E.MANAGER_ID
START WITH E.MANAGER_ID IS NULL
ORDER BY LEVEL;


